INSERT INTO app.medicines (version, medicine_name, medicine_type, medicine_description)
VALUES
    (0, 'Paracetamol', 'ANALGESIC', 'Used for pain relief and fever reduction'),
    (0, 'Amoxicillin', 'ANTIBIOTIC', 'Common antibiotic for bacterial infections'),
    (0, 'Ibuprofen', 'ANTI-INFLAMMATORY', 'Reduces pain, fever, and inflammation'),
    (0, 'Cetirizine', 'ANTIHISTAMINE', 'Used to treat allergies'),
    (0, 'Omeprazole', 'PROTON_PUMP_INHIBITOR', 'Reduces stomach acid production'),
    (0, 'Metformin', 'ANTIDIABETIC', 'Used to treat type 2 diabetes'),
    (0, 'Salbutamol', 'BRONCHODILATOR', 'Relieves asthma symptoms'),
    (0, 'Atorvastatin', 'STATIN', 'Used to lower cholesterol'),
    (0, 'Levothyroxine', 'HORMONE', 'Treats hypothyroidism'),
    (0, 'Aspirin', 'ANTIPLATELET', 'Reduces blood clot risk and relieves pain'),
    (0, 'Losartan', 'ANTIHYPERTENSIVE', 'Used to manage high blood pressure'),
    (0, 'Simvastatin', 'STATIN', 'Helps lower cholesterol levels'),
    (0, 'Ciprofloxacin', 'ANTIBIOTIC', 'Broad-spectrum antibiotic for bacterial infections'),
    (0, 'Ranitidine', 'ANTACID', 'Reduces stomach acid'),
    (0, 'Dexamethasone', 'CORTICOSTEROID', 'Reduces inflammation and suppresses the immune system'),
    (0, 'Albuterol', 'BRONCHODILATOR', 'Relieves bronchospasms'),
    (0, 'Furosemide', 'DIURETIC', 'Treats fluid retention and swelling'),
    (0, 'Warfarin', 'ANTICOAGULANT', 'Prevents blood clots'),
    (0, 'Clopidogrel', 'ANTIPLATELET', 'Prevents heart attack and stroke'),
    (0, 'Hydrochlorothiazide', 'DIURETIC', 'Treats high blood pressure and fluid retention'),
    (0, 'Pantoprazole', 'PROTON_PUMP_INHIBITOR', 'Treats acid reflux and ulcers'),
    (0, 'Montelukast', 'LEUKOTRIENE_RECEPTOR_ANTAGONIST', 'Used to manage asthma and allergies'),
    (0, 'Spironolactone', 'DIURETIC', 'Treats heart failure and fluid retention'),
    (0, 'Fluticasone', 'CORTICOSTEROID', 'Used for asthma and allergic rhinitis'),
    (0, 'Rosuvastatin', 'STATIN', 'Reduces cholesterol levels'),
    (0, 'Venlafaxine', 'ANTIDEPRESSANT', 'Used for depression and anxiety'),
    (0, 'Sertraline', 'ANTIDEPRESSANT', 'Treats depression and obsessive-compulsive disorder'),
    (0, 'Zolpidem', 'SEDATIVE', 'Treats insomnia'),
    (0, 'Gabapentin', 'ANTICONVULSANT', 'Treats nerve pain and seizures'),
    (0, 'Doxycycline', 'ANTIBIOTIC', 'Used for bacterial infections and acne'),
    (0, 'Prednisone', 'CORTICOSTEROID', 'Reduces inflammation and suppresses immune responses'),
    (0, 'Propranolol', 'BETA_BLOCKER', 'Treats high blood pressure and anxiety'),
    (0, 'Insulin Glargine', 'ANTIDIABETIC', 'Long-acting insulin for diabetes management'),
    (0, 'Tamsulosin', 'ALPHA_BLOCKER', 'Used for prostate gland enlargement'),
    (0, 'Lisinopril', 'ANTIHYPERTENSIVE', 'Manages high blood pressure and heart failure'),
    (0, 'Amlodipine', 'ANTIHYPERTENSIVE', 'Treats high blood pressure and chest pain'),
    (0, 'Esomeprazole', 'PROTON_PUMP_INHIBITOR', 'Treats acid reflux and ulcers'),
    (0, 'Methotrexate', 'IMMUNOSUPPRESSANT', 'Used for rheumatoid arthritis and cancer'),
    (0, 'Levofloxacin', 'ANTIBIOTIC', 'Broad-spectrum antibiotic for bacterial infections'),
    (0, 'Diclofenac', 'ANTI-INFLAMMATORY', 'Treats pain and inflammation'),
    (0, 'Rivaroxaban', 'ANTICOAGULANT', 'Prevents blood clots'),
    (0, 'Mometasone', 'CORTICOSTEROID', 'Treats nasal allergies and skin conditions'),
    (0, 'Bisoprolol', 'BETA_BLOCKER', 'Used for high blood pressure and heart conditions'),
    (0, 'Carbamazepine', 'ANTICONVULSANT', 'Treats epilepsy and nerve pain'),
    (0, 'Topiramate', 'ANTICONVULSANT', 'Used for seizures and migraine prevention'),
    (0, 'Lamotrigine', 'ANTICONVULSANT', 'Treats bipolar disorder and epilepsy'),
    (0, 'Tramadol', 'ANALGESIC', 'Relieves moderate to severe pain'),
    (0, 'Hydrocodone', 'ANALGESIC', 'Used for severe pain management'),
    (0, 'Fentanyl', 'ANALGESIC', 'Strong pain reliever for severe conditions'),
    (0, 'Morphine', 'ANALGESIC', 'Used for severe pain relief');
