# Generated by Django 5.1.2 on 2024-10-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_osoba_data_dodania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='plec',
            field=models.CharField(choices=[(1, 'Kobieta'), (2, 'Mężczyzna'), (3, 'Inne')], max_length=1),
        ),
    ]
