package com.example.appwww.Models.Enums;

public enum MedicineType {
    ANALGESIC,
    ANTIBIOTIC,
    ANTI_INFLAMMATORY,
    ANTIHISTAMINE,
    PROTON_PUMP_INHIBITOR,
    ANTIDIABETIC,
    BRONCHODILATOR,
    STATIN,
    HORMONE,
    ANTIPLATELET,
    ANTIHYPERTENSIVE,
    ANTACID,
    CORTICOSTEROID,
    DIURETIC,
    LEUKOTRIENE_RECEPTOR_ANTAGONIST,
    ANTIDEPRESSANT,
    SEDATIVE,
    ANTICONVULSANT,
    BETA_BLOCKER,
    IMMUNOSUPPRESSANT,
    ALPHA_BLOCKER,
    ANTICOAGULANT
}
